- id: check-rebased-merge
  name: Ensure branch is rebased on develop
  entry: bin/rebase-check
  language: script
  stages: [merge-commit]
  description: |
    Blocks local merges if the branch being merged is not rebased on 'develop'.
    Automatically skipped in CI.
