- id: rip0005-gitflow
  name: RIP 5 GitFlow
  entry: bin/rip0005-gitflow.sh
  language: script
  pass_filenames: true
  always_run: true
  stages: [pre-push, commit-msg]
  description: |
      Routes RIP 5 checks to the appropriate scripts for `pre-push` and
      `commit-msg`.
